### ISSUE TITLE
Provide scripts for Debian-based distros

### ISSUE THREAD

**Issue by davecollett** [icsm-au/DynAdjust#1]
Current scripts only support installing prerequisites using DNF. Suggest support for Debian-based distros such as Ubuntu.

I have added some modified files to enable this in Ubuntu 18.04. Unfortunately I'm not able to fully build DynAdjust due to a lack of RAM.
Fork with changes here:
https://github.com/davecollett/DynAdjust/tree/ubunutu-build-scripts/dynadjust

**Comment by harry093** [comment]
Thanks Dave. Could you submit a pull request?

How much RAM is required to build DynAdjust?
