### ISSUE TITLE
--iteration threshold switch for adjust.exe

### ISSUE THREAD

**Issue by slatham64** [icsm-au/DynAdjust#12]
If the --precision-stn-linear default is 4 (linear coordinates are published to four decimal places) should the default iteration threshold be 0.00005m not 0.0005m.

**Comment by harry093** [comment]
I don't think this is an issue. --precision-stn-linear, as you say, relates to the published precision of the station coordinates, not the precision used for the calculations.

@rogerfraser, if you are happy with my comment could you please close this issue.
