### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by davidgreavesau** [icsm-au/DynAdjust#14]
I have been trying to run plot.exe and I think there are some other dependencies might needed?

So far I've installed these 3 and it seems to be getting close. I'm not sure if there are others required?
- gmt ( unsure of version as 5.4.5 is showing deprecated commands)
- ghostscript
- epstool

**Comment by harry093** [comment]
Hi @davidgreavesau, could you provide the error message you are getting?

**Comment by davidgreavesau** [comment]
Sure here you go.

[plot error.txt](https://github.com/icsm-au/DynAdjust/files/3051400/plot.error.txt)

**Comment by harry093** [comment]
Thanks. Looking at that output it does look like you have too new a version of GMT. There are plenty of deprecation warnings, as you note, but the most concerning is the line:

gmtset: Production of EPS format is no longer supported, remove + after paper size

AFAIK, all that is needed is GMT, esptool and gnuplot. I use GMT 4.5.9, epstool 3.08, and gnuplot 4.6.3. Try running with these and see how you go.

**Comment by rogerfraser** [comment]
At this stage, DynAdjust plot provides support for GMT 4.x versions. GMT 5 introduced major changes to the API and as a consequence, the command files produced by plot cannot be used with GMT 5.x.

Plans are in place to add support for GMT 5.

**Comment by davidgreavesau** [comment]
Thanks. I will download those versions and remove ghost script and see how I go.

**Comment by davidgreavesau** [comment]
It seems to need ghostscript in windows 10 at least as without it you get a ps2pdf error?

[Without Ghostscript.txt](https://github.com/icsm-au/DynAdjust/files/3052604/Without.Ghostscript.txt)
[With Ghostscript.txt](https://github.com/icsm-au/DynAdjust/files/3052605/With.Ghostscript.txt)

It seems to be getting close now with the older GMT but for some reason it is looking for the stn.d file in the folder I run the batch file from?
_+ Creating EPS... Could Not Find C:\SharedData\DynAdjust\david.stn.d_

**Comment by wapayze** [comment]
plot also isn't plotting for me.
Below is a text file of the output when I run plot from the command line.
It didn't capture all of it so I added the extra output below.
Regarding epstool and ps2pdf not being recognized, they are installed.
I've added them to PATH as that was the only thing I could think to do.

[plot_test.txt](https://github.com/icsm-au/DynAdjust/files/3067265/plot_test.txt)

**Comment by davidgreavesau** [comment]
I had the pscoast error as well.
I download the GSHHG files gor GTM and then set an enviroment variable (DIR_GSHHG) to where they were and it went away.  https://www.soest.hawaii.edu/pwessel/gshhg/ has a download

**Comment by rogerfraser** [comment]
Good pickup David. I believe GSHHG was separated from GMT as part of GMT modernisation. 

In addition, you’ll need to install the following programs:
- epstool - (http://www.ghostgum.com.au/software/epstool.htm)
- postscript - (https://www.ghostscript.com/download/gsdnld.html) 

epstool will be contained in a zip or tar, and can be extracted to a “utilities” folder, or similar (e.g. C:\data\utils\”)

Once ghostscript is installed, you’ll need to add the following environment variables to your system path:
•	<installation folder for gs>\lib\
•	<installation folder for gs>\bin\
•	C:\data\utils\
