### ISSUE TITLE
Extending discontinuity renaming functionality

### ISSUE THREAD

**Issue by harry093** [icsm-au/DynAdjust#15]
The new functionality to rename stations with discontinuities on-the-fly works well for SINEX files. Could this functionality be extended to also:
* rename stations in other file types (DNA and DynaML); and
* take renaming into account when:
  * specifying stations to constrain from the command line; and
  * specifying stations to include or exclude form the command line.

**Comment by rogerfraser** [comment]
@harry093 - although the majority of this issue has been resolved, I'm leaving this issue open since there is a little more work to do to satisfy the requirement to rename discontinuity stations when "specifying stations to constrain from the (**adjust**) command line".

**Comment by harry093** [comment]
No problems @rogerfraser that is a tricky one. Good work!
