### ISSUE TITLE
Deflection of vertical correction incorrectly applied to zenith angles

### ISSUE THREAD

**Issue by nicgowans** [icsm-au/DynAdjust#160]
Equation 7.36 in the DynAdjust manual has been erroneously reproduced from Hofmann–Wellenhof and Moritz (2006).

The correction for the deflection of the vertical of zenith angles (type V) should be added instead of subtracted.

Note: Vertical angles (type Z) are not affected by this error. Eqn 7.39 is correct in subtracting the deflection of the vertical correction (V and Z msr types being complementary angles).

**Comment by rogerfraser** [comment]
Thanks @nicgowans for raising this. This will be addressed in the next release.
