### ISSUE TITLE
Unexpected behaviour in output of Adjusted Coordinates table

### ISSUE THREAD

**Issue by jameslevershadelwp** [icsm-au/DynAdjust#168]
**Description**
An issue with running dnaadjust where options are set as ENzPLHhXYZ and --stn-corrections is set. The SD(e)(n)(up) columns are merging together and then the remaining columns are out of line. 

Running DNA v 1.1.0

**Steps to reproduce**
To reproduce the unexpected behaviour:
1. Execute **program** using the following commands:
```
program [options] [files] ...

Command line arguments:            /usr/local/bin/dnaadjust AP079465H --output-adj-msr --dms-msr-format 2 --stn-coord-types ENzPLHhXYZ --stn-corrections --max-iterations 100 --iteration-threshold .0005 


**Expected behaviour**
Columns lining up with the values


**Screenshots**
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/49735855/141868719-2262f40a-39ff-4933-8dff-ca9c03db8160.png">

**Operating system**
Apple

**Additional context*
[stn_msr.zip](https://github.com/icsm-au/DynAdjust/files/7542237/stn_msr.zip)
*
Add any other context about the problem here.

**Comment by jameslevershadelwp** [comment]
seems to happen any time --stn-corrections is used

**Comment by rogerfraser** [comment]
Thanks @jameslevershadelwp.  I see this an issue for 1.1.0.  Can you please confirm if this is still an issue for [version 1.2.2](https://github.com/icsm-au/DynAdjust/releases/tag/v1.2.2)?
