### ISSUE TITLE
Unexpected behaviour in printing results to the file when using --output-adj-gnss-units 1

### ISSUE THREAD

**Issue by ibaran73** [icsm-au/DynAdjust#169]
When adjustment is executed with the option `--output-adj-gnss-units' set to 1 (enu), DynAdjust exits prematurely during the printing phase and the *.adj file is incomplete.

Note the difference in the *.adj file for the same adjustment with different argument of the option `--output-adj-gnss-units':

1. Setting with argument 0 (XYZ):  `--output-adj-gnss-units 0':

M Station 1           Station 2           Station 3           *  C            Measured           Adjusted  Correction     Meas. SD      Adj. SD     Corr. SD     N-stat  Pelzer Rel  Pre Adj Corr    Outlier?
G 3588957             4952884                                    X          -1191.8005         -1191.8111     -0.0106       0.0050       0.0038       0.0033      -3.21        1.52        0.0000           *
G 3588957             4952884                                    Y           2003.5072          2003.5145      0.0073       0.0110       0.0074       0.0081       0.90        1.35        0.0000            
G 3588957             4952884                                    Z           3745.8424          3745.8405     -0.0019       0.0058       0.0048       0.0033      -0.59        1.76        0.0000            
G 3588957             4953733                                    X          -6481.7252         -6481.7251      0.0001       0.0135       0.0033       0.0131       0.01        1.03        0.0000            
G 3588957             4953733                                    Y           -671.4561          -671.4351      0.0210       0.0230       0.0057       0.0223       0.94        1.03        0.0000            
G 3588957             4953733                                    Z           3671.8569          3671.8201     -0.0368       0.0251       0.0045       0.0247      -1.49        1.02        0.0000            
G 3588957             4952894                                    X            609.2062           609.2137      0.0075       0.0062       0.0044       0.0044       1.72        1.42        0.0000            
G 3588957             4952894                                    Y          -1160.3815         -1160.3919     -0.0104       0.0106       0.0075       0.0076      -1.37        1.41        0.0000            
G 3588957             4952894                                    Z          -2081.7101         -2081.6982      0.0119       0.0110       0.0057       0.0094       1.26        1.17        0.0000            
G 3588957             4952887                                    X          -4976.0953         -4976.0957     -0.0004       0.0142       0.0040       0.0136      -0.03        1.04        0.0000            
G 3588957             4952887                                    Y          -3926.4036         -3926.3883      0.0153       0.0208       0.0058       0.0200       0.76        1.04        0.0000 

2. Setting with argument 1 (enu): `--output-adj-gnss-units 1':

M Station 1           Station 2           Station 3           *  C            Measured           Adjusted  Correction     Meas. SD      Adj. SD     Corr. SD     N-stat  Pelzer Rel  Pre Adj Corr    Outlier?
G 3588957             4952884                                    e            194.7301           194.7364      0.0064       0.0044       0.0077    -nan(ind)  -nan(ind)   -nan(ind)        0.0000            
G 3588957             4952884                                    n           4407.7024          4407.7067      0.0042       0.0044    -nan(ind)       0.0074       0.58        0.60        0.0000            
G 3588957             4952884                                    u              2.1090             2.1196      0.0106       0.0119       0.0161    -nan(ind)  -nan(ind)   -nan(ind)        0.0000            
G 3588957             4953733                                    e           6121.8407          6121.8315     -0.0093       0.0082    -nan(ind)       0.0088      -1.06        0.93        0.0000            
G 3588957             4953733                                    n           4297.4366          4297.4152     -0.0214       0.0112       0.0078       0.0080      -2.66        1.39        0.0000           *
G 3588957             4953733                                    u            -35.3945           -35.3591      0.0354       0.0339    -nan(ind)       0.0340       1.04        1.00        0.0000            
G 3588957             4952894                                    e            -39.9032           -39.9054     -0.0022       0.0043       0.0000       0.0043      -0.52        1.00        0.0000            
G 3588957             4952894                                    n          -2459.5209         -2459.5174      0.0034       0.0051       0.0000       0.0051       0.68        1.00        0.0000            
G 3588957             4952894                                    u            -17.2970           -17.3140     -0.0170       0.0151       0.0000       0.0151      -1.12        1.00        0.0000            
G 3588957             4952887                                    e           6192.6453          6192.6390     -0.0063       0.0128       0.0000       0.0128      -0.49        1.00        0.0000            
G 3588957             4952887                                    n          -2498.4678         -2498.4662      0.0016       0.0107       0.0000       0.0107       0.15        1.00        0.0000            
G 3588957             4952887                                    u            -43.2224           -43.2070      0.0154       0.0239       0.0000       0.0239       0.64        1.00        0.0000 

Note  how 'Meas. SD, Adj. SD, Corr. SD' may display incorrect values:  "-nan(ind)" or "0.0000" 
It is very difficult to pinpoint the reason for this behaviour.
Thank you for looking into it.

**Comment by rogerfraser** [comment]
Thanks @ibaran73.  Could you please upload some example input files to replicate this defect. Many thanks

**Comment by ibaran73** [comment]
Thank you @rogerfraser for looking into it. Here are the example input files:
Initial coordinates:
[20211118_WA_GDA2020.phased-stage.adj.zip](https://github.com/icsm-au/DynAdjust/files/7715549/20211118_WA_GDA2020.phased-stage.adj.zip)
Measurements:
[20211118_WA_GDA2020_msr.zip](https://github.com/icsm-au/DynAdjust/files/7715568/20211118_WA_GDA2020_msr.zip)
Command line:
adjust 20211118_WA_GDA2020 --staged  --create-stage-files --output-adj-msr --output-adj-gnss-units 1 --stn-coord-types ENzPLHhXYZ --export-xml --max-iterations 1
