### ISSUE TITLE
Adj measure results can overflow column width when values are negative

### ISSUE THREAD

**Issue by thollands** [icsm-au/DynAdjust#179]
**Description**

Measure results in the .adj file can exceed column width when value is less than 0 - i.e. it has a negative value. Observed on "correction" column, but may be present elsewhere. 

Running dynadjust release v1.2.3 on Windows

**Steps to reproduce**
See attached example data - dynadjust commands run are available in imp, seg and adj files. (sorry - had to rename them to TXT for github)

[00ff7276a19147f0848fe235bb23858c.imp.txt](https://github.com/icsm-au/DynAdjust/files/8424208/00ff7276a19147f0848fe235bb23858c.imp.txt)
[00ff7276a19147f0848fe235bb23858c.phased.adj.txt](https://github.com/icsm-au/DynAdjust/files/8424210/00ff7276a19147f0848fe235bb23858c.phased.adj.txt)
[00ff7276a19147f0848fe235bb23858c.seg.txt](https://github.com/icsm-au/DynAdjust/files/8424211/00ff7276a19147f0848fe235bb23858c.seg.txt)
[msr_20220331-120231.xml.txt](https://github.com/icsm-au/DynAdjust/files/8424212/msr_20220331-120231.xml.txt)
[stn_20220331-120232.xml.txt](https://github.com/icsm-au/DynAdjust/files/8424216/stn_20220331-120232.xml.txt)

Adj file contains example overflow on line 87 in correction column like this:
```
M Station 1           Station 2           Station 3           *  C            Measured           Adjusted  Correction     Meas. SD      Adj. SD     Corr. SD     N-stat     T-stat  Pelzer Rel  Pre Adj Corr    Outlier?  Meas. ID Clust. ID
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
D 340500141633        340500141684                               1                                                                                                                                                        34461957         0
                                          340500141676                    305.13000000        17.21427273-1036277.2727   15292.9110    6831.1434   13682.4196     -75.74     -42.97        1.12        0.0000           *  34461957         0
```
**Expected behaviour**
Rounding the correction value -1036277.2727 to a number that fits within its 12 character width - either scientific notation or decimal rounding

Thanks in advance!

**Comment by rogerfraser** [comment]
Thanks for raising this @thollands - I'll investigate and aim for this to be addressed for the next release.
