### ISSUE TITLE
geoid.exe --verbose option does NOT currently result in a log file.  (Does this affect other DynAdjust exe too?) (v 1.2.6, 06 SEPT) 

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#186]
ISSUE TYPE: Functional failure
URGENCY:  Moderate

**Description**
**geoid.exe** run with --verbose does NOT result in a log file. 
The expectation (per the Users Guide) is that --verbose result in a log file “when station(s) lie outside extents?”   
[Aside: Does this mean “only when”?]
Refer to Users Guide Section C.4 Geoid interpolation log file
[Alas GitHub is currently returning an error when I try to attach a screen shot - Yes I know it SHOULD work ;-)]

**Steps to reproduce**
INPUT(S):
- [geoid-points-dat.txt](https://github.com/icsm-au/DynAdjust/files/9498748/geoid-points-dat.txt) (from SampleData) - this file already contains stations designed to be ‘outside extents’ , as in: 
- AUSGeoid09_V1.01.gsb (from GeoscienceAustralia ‘agrstoolsandmodels’)

COMMANDS (command line):
- geoid -g AUSGeoid09_V1.01.gsb -t geoid-points-dat.txt --verbose 0
- geoid -g AUSGeoid09_V1.01.gsb -t geoid-points-dat.txt --verbose 3
	
OUTPUT(S):
-	geoid-points-dat_out.txt    [Rename each file as it is produced to avoid overwriting by next command]
-	Review the above output files. These contain the same output regardless of --verbose-level (This is expected)
-	There is NO log file created (This is NOT expected.

**Expected behaviour / Recommendation**
1. A log file output is expected when using --verbose option.
2. Review if similar issue affects other DynAdjust exe files 

**Operating system**
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au for raising this.

Just to confirm behaviour, both expected and actual, when (1) importing geoid information and (2) during text file mode.

**1. Importing geoid information into a project.**
  - When importing geoid information, if a point lies outside the extents of the supplied geoid file, no information will be retrieved for that point.  In this instance, by default, a geoid interpolation log file (*.int) will not be produced.  To view the stations for which geoid information could not be interpolated, the option `--verbose` with a value greater than zero must be provided.  This will result in a geoid interpolation log file.  By way of example, the following message is printed on the command line when a point lies outside the grid file, and the `--verbose`  option has not been provided:
  ```
  - Warning: Data for 13 stations could not be interpolated.  To view the list of stations
    for which a height could not be interpolated, call geoid with --verbose-level 1.
  ```
  - If the `--verbose`  option has been provided, then the following message will be printed on the command line:
  ```
    - Warning: Data for 13 stations could not be interpolated.
    See .\50ke.int to view the list of stations for which an
    N-value could not be interpolated.
  ```

  - I see this behaviour as expected and consistent with the documentation in section 5.4.

**2. Text file mode.**
  - When interpolating geoid information for a list of points in a text file and a point lies outside a grid file, the output text file will contain an error message for that point.  For example:
  ```
  ERROR (-1): The point "-38.0656499900, 145.1052501400" lies outside the extents of the specified grid file.
  ```

  - While different to the bevaviour of 1. above, this is consistent with the documentation in section 5.5.

From my perspective, I suggest the documentation be made more clear in both sections 5.4 and 5.5.

In the case of 2. above, if there is a need for a geoid interpolation log file (*.int) **in addition to** error messages being printed to the output text file, then this calls for a "feature improve".  If there isn't a strong need for this improvement, I suggest either closing this issue or marking this as low priority.

Thoughts?

**Comment by jhaasdyk-au** [comment]
Apologies for the slow reply. 
You have likely progressed this already, many thanks.
At this stage I cannot access your release candidate binaries or manual, so I reply only to your question above.


I agree that upon a FULL reading and cross checking of the documentation, the current behaviors match the documentation. 

The source of my confusion arose perhaps from STARTING my reading at Section C.4, which states more categorically 
_"A geoid interpolation log (.int) file will be created by geoid when --verbose-level has been supplied with an argument greater than 0, and will contain information when any station lies outside the extents of the geoid grid file"_
I failed to then adequately dig into the more subtle differences which might be expected between project, text file or interactive modes.

Thoughts on actions:
1) Yes, an update to documentation **(perhaps also at C.4)** would help avoid that issue for others.,
2) No. I don't see a need for the geoid interpolation log file in addition. I simply went looking for one because the documentation suggested (as I read it) to look there.
3) I am happy for this ticket to be closed or re-prioritized. As previously noted, I do not have permissions to do so.

**Comment by jhaasdyk-au** [comment]
I now have access to the updated 1.2.7.rc4 User Manual.
I think this whole issue could be addressed with a small change to the start of Section C.4 (only).

C.4 Geoid interpolation log file (INT)
A geoid interpolation log (.int) file will be created within a project by **geoid** if --verbose-level has been supplied with an argument greater than 0. The log file will contain information when any station lies outside the extents of the geoid grid file.  When using **geoid** in interactive or text file mode (c.f. _Section_ 5.5) error logs will appear directly in the output from **geoid** rather than in a separate log file.

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au.  I've applied your suggestion to the User's Guide (on my fork), which will appear in 1.2.7.
