### ISSUE TITLE
geoid.exe --verbose option: Request for command line reference to indicate that output is to be directed to log file. (v 1.2.6, 06 SEPT) 

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#187]
ISSUE TYPE: User experience improvement
URGENCY:  NOT urgent
PRIORITY: LOW

**Description**
As a new user of **geoid.exe** (and likely other DynAdjust.exe) it is not obvious that the --verbose option will direct the additional output to a log file, rather than reported the information back at the command line. 
[Refer to geoid --help output at --verbose option]

The Users Guide gives a better indication (in various sections) that --verbose will result in a LOG file instead. (e.g. for geoid.exe, reftran.exe).

**Expected behaviour / Recommendation**
REQUEST:
1. Update --verbose description in command line referencing to indicate the result of option --verbose.
“Give detailed information in the log file about what xxxxx is doing.”

**Operating Environment**
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au. I agree, this could be better.  The command line text has been updated with the following, and will appear in the next release.

```
  --verbose-level arg      When importing geoid information into a project, print the
                           stations for which an N-value could not be interpolated to a
                           log (*.int) file.
                             0: No information (default)
                             1: Helpful information
                             2: Extended information
```

**Comment by jhaasdyk-au** [comment]
Done, in updated 1.2.7.rc4 User Manual

This message is to test if I can successfully use the 'close with comment' button on this thread.
