### ISSUE TITLE
geoid.exe: Request for more instruction on input text file formats in command line referencing  (v 1.2.6, 06 SEPT)

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#189]
ISSUE TYPE: User experience improvement
URGENCY:  NOT urgent
PRIORITY: LOW

**Description**
As a ‘new’ user of **geoid.exe**, I would benefit from having more instruction in the command line referencing to tell me that there are restrictions on file types accepted when using option --text-file (text file mode).
Input is restricted to “Formatted Text files (e.g. *.dat, *.prn, *.txt, and *.csv) of a specific format only.
I now know that there is a wealth of information in the Users Guide, but before that knowledge I spent some fruitless effort on trial and error.
o	B.6 Geoid input text files with sample format
o	geoid-points-dat.txt in the sampleData.
o	Section 5.5.1 Interactive mode (Chapter 5, Import and Export of Geoid)
o	Section 5.5.2 Text file mode. 

**Steps to reproduce**
Not applicable

**Expected behaviour / Recommendation**
REQUEST:
1. Improve / expand on instructions at the following touch points ( screen shots available, but I can't attach them here!]
Consider wording such as: “Perform geoid interpolation from coordinates contained in a text file (refer to DynAdjust User’s Guide for file format information)
 - i.	User’s Guide Table A.14 
 - ii.	Command line referencing (same changes as above)
 - iii.	"Error: Cannot read this type of input file" reported at CMD line (geoid.exe output)  (e.g. when input file types is other than .txt)
 - iv.	Append to output file when input file errors are noted.

**Operating Environment**
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au.  The command line text has been updated as follows, and will appear in the next release:

```
-t [ --text-file ] arg             Interpolate geoid information using coordinates contained in a
                                   text file. arg is the path of the input text file. The
                                   supported text file formats include formatted text (*.txt) and
                                   comma separated values (*.csv) files. Refer to the User's
                                   Guide for file format information.
```

These changes include updates to the User's Guide.

**Comment by jhaasdyk-au** [comment]
Thank you @rogerfraser for these changes in the 1.2.7.rc4 binaries and User Guide
