### ISSUE TITLE
Import data in CSV format

### ISSUE THREAD

**Issue by gnssgrid** [icsm-au/DynAdjust#19]
Hi
It would be nice to have option to import data in ASCII format

**Comment by harry093** [comment]
Hi @gnssgrid, by ASCII format do you mean comma separated values format?

**Comment by gnssgrid** [comment]
yes
I think that it is more practical. If I want to import my observations and coordinates I must create files manually or wrote program to convert it to DNA file format

**Comment by BatchelorJ** [comment]
Hi @gnssgrid, thanks for your suggestion. While we think it would be great to support comma separated values, it would be a huge challenge to support all the different measurement types and ensure they came into DynAdjust correctly. I've done some work converting native data from total stations to DynAdjust using Python, and if you're interested you can see this here: [https://github.com/GeoscienceAustralia/GeodePy/tree/master/geodepy/surveyconvert](url)

**Comment by rogerfraser** [comment]
This issue has been conflated with issues https://github.com/icsm-au/DynAdjust/issues/3 and https://github.com/icsm-au/DynAdjust/issues/22, and repurposed as issue https://github.com/icsm-au/DynAdjust/issues/51
