### ISSUE TITLE
geoid.exe --text-file mode:  should report the direction for conversion of heights.  (v 1.2.6, 06 SEPT)

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#190]
ISSUE TYPE: User experience improvement
URGENCY:  NOT urgent
PRIORITY: Moderate

**Description**
**geoid.exe** does not currently report the direction for conversion of heights to command line reporting during execution.
(i.e. Orthometric to Ellipsoid, or Ellipsoid to Orthometric)
Ideally, this should be reported when using option --text-file (text file mode), which can convert in either direction.

**Steps to reproduce**
INPUT(S):	
- [skye_lat_long_formatted.txt](https://github.com/icsm-au/DynAdjust/files/9498964/skye_lat_long_formatted.txt)
- AUSGeoid09_V1.01.gsb (from GeoscienceAustralia ‘agrstoolsandmodels’)

COMMANDS (command line):
- geoid -g AUSGeoid09_V1.01.gsb -t skye_lat_long_formatted.txt --direction 0
- geoid -g AUSGeoid09_V1.01.gsb -t skye_lat_long_formatted.txt --direction 1

OUTPUT(S): 
- skye_lat_long_formatted_out.txt   [Ignore output files for this issue]
- Review command line reporting.
- CMD line reporting is same for both options; The echo of options does NOT report the conversion direction.
  [Alas GitHub is currently returning an error when I try to attach a screen shot - Yes I know it SHOULD work ;-)]

**Expected behaviour / Recommendation**
	RECOMMEND:
1. Text File mode: The file interpolation direction should be explicitly echoed back to the user. (incl default state)
2. Interactive mode: An additional feature could be to have this model accept an (optional) --height value as input.   
After all, why treat interactive and text file input modes differently?
_If_ height for interactive mode were adopted, then the same should apply: provide verbose feedback on conversion direction. 
3. NOTE: No change for default mode:  if using --convert-stn-hts:  Section 5.4. describes the operation (without user defined options), and actions are already reported back to user at command line (i.e. per Figure 5.4 "... reducing heights to the ellipsoid" )

Operating Environment
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au. The suggestion for reporting interpolation direction has been implemented on my fork and will appear in the next release.
