### ISSUE TITLE
Minor typographic errors

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#191]
ISSUE TYPE: Minor typographic error(s).
URGENCY:  NOT urgent

Record any such error via the comments below. 
If the issue is 'Closed' you may want to contact an administrator to re-open the issue.

**Comment by jhaasdyk-au** [comment]
This issue is updated 09/09 to be a general catch-all for typographical errors in  the text.  
(Original issue referred to a single error only]

**Comment by jhaasdyk-au** [comment]
**geoid.exe**  command line referencing contains a typo at option --direction: “Ellispoid” [sic]
_geoid --help_  command will demonstrate this error.
Note: DynAdjust Users Guide does NOT contain this typo.

**Operating Environment**
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by jhaasdyk-au** [comment]
Section 3.3.1 Reference frame / Default Reference frame.
The subsection title should only have the first word capitalised: i.e. Default Reference frame =>  Default reference frame

I'm channeling my 'inner-german' today ;-)

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au. These changes have been made on my copies and will appear in the next release.
