### ISSUE TITLE
Update 'Skye' tutorial documentation to reflect changes to code, defaults, and SampleData (v 1.2.6, 06 SEPT) 

### ISSUE THREAD

**Issue by jhaasdyk-au** [icsm-au/DynAdjust#193]
PRIORITY: Moderate / High

**Brief description**
As a 'new-again' user, I am reviewing the many new features and documentation available for DynAdjust.
The quick intro tutorial ('Skye') is the first obvious step.
As I run this tutorial, I note a few issues where the Skye tutorial documentation could / should be updated to reflect changes in code, (e.g. the effect of now having GDA2020 as the default reference frame) and sample files.

**Expected behaviour / Recommendations**
** for updates to User Guid, Section 1.4 Tutorial**
1. In Section 1.4 'Step 2 (Import the data)'  Sample files are documented as 2009-10-20-skye.stn  (& msr)
It appears these have since been renamed to skye-tutorial.stn (& msr) at [https://github.com/icsm-au/DynAdjust/tree/master/sampleData](https://github.com/icsm-au/DynAdjust/tree/master/sampleData)

2. Consider describing in 'Step 1 (Prepare...)' where to find the tutorial files. 
e.g. in Section 4.6.3 you say (‘…download from the sampleData folder in the GitHub repository’,
and the link is provided in that Section. https://github.com/icsm-au/DynAdjust/tree/master/sampleData''
Consider perhaps a new Appendix describing all the available SampleData, and just refer to that Appendix from elsewhere in the document.

3. At 'Step 2 (Import the data)' complete this list in the User Guide: 
   “… several files will be written to disk: skye.bst, skye.bms, skye.map, skye.asl, skye.aml and skye.imp."
i.e. Do Include also the (new? Or new-to-me) skye.dbid

4. At 'Step 2 (Import the data)', given the command (which defaults now to GDA2020 as the default reference frame)
   _import -n skye 2009-10-20-skye.stn 2009-10-20-skye.msr_
   - Update the document in this Section to indicate that a  **Warning** will be obtaining in command line output and in skye.imp 
   " Warning: Input file reference frame (GDA94) does not match the  default reference frame."
   - … and provide instruction on how to over-ride that default with GDA94 [otherwise you'll have a datum and geoid mismatch later in the tutorial)
That’s actually a great learning from the initial quick tutorial!
     [Addendum 09/09/2020:
       - It might not be perfectly obvious, but there there is not actually a datum and geoid mismatch in this tutorial (because the imported GNSS measurements retain their nominal datums) at the time that geoid is run.  Other example(s) run reftran before geoid (probably prudent), but  this would require careful consideration of the geoid employed.;
        - However there is (currently) a discrepancy in the reported adjfile and adjust.exe reporting of epoch (link to related discussion)
        - Recommend to include in the tutorial "For more information on managing reference frames, refer to Section 3.3.1"]

5. At Step 3 (Introduce geoid-ellipsoid separations) ausgeoid09.gsb is introduced.
However ausgeoid09.gsb is not supplied in the sampleData folder. (rather ausgeoid09_gda94_v1.01_clip_1x1.dat is supplied).
The supplied geoid command _geoid skye -g ./ausgeoid09.gsb --convert-stn-hts_ cannot therefore be completed (at least not without other instruction)
I recommend to:
   - supply AUSGeoid09_V1.01.gsb (and also the latest AUSGeoid2020 in sampleData
   - update the text / command in Step 3 accordingly.
   - Note: Download of AUSGEOID from GA is (now) named AUSGeoid09_V1.01.gsb (in agreement with EPSG https://epsg.org/transformation_5656/GDA94-to-AHD-height-49.html )

6. I initially reported here that some quick testing in an attempt to break the tutorial returned some unexpected behaviour when mixing and matching defaults reference frames and geoid files. 
After cleaning up that data a bit more in to a systematic batch file, I cannot reproduce those errors.
[skye_tutorial_test_datum_geoid.txt](https://github.com/icsm-au/DynAdjust/files/9532098/skye_tutorial_test_datum_geoid.txt) (rename to .bat to run as batch file).
However, it does highlight a discrepancy regarding reference frame and epoch reporting, discussed at [#200](https://github.com/icsm-au/DynAdjust/discussions/200#discussion-4377064)

7. I think there is reason to consider a 2nd slightly more extensive tutorial, which introduces data from multiple reference frames in a single file, multiple data files of different reference frames, reftran, the effect of running retran on choice of geoid, and a few other idiosyncracies.  This could be placed in an appendix. This might clear up some of the question now raised at the linked discussion in #6 above.

**Operating Environment**
Windows 10 Enterprise
DynAdjust v1.2.6
DynAdjust Users Guide.PDF (‘Sept 2022’) gather 06/SEPT/2022 from fork [rogerfraser/DynAdjust](https://github.com/rogerfraser/DynAdjust)

**Comment by jhaasdyk-au** [comment]
Modified #4 above. 
Modified #6 above.
Added #7

**Comment by rogerfraser** [comment]
Thanks @jhaasdyk-au. Fixes to address these points will be included in the next release.

**Comment by jhaasdyk-au** [comment]
New material cited in 1.2.7.rc4.
Many thanks @rogerfraser
