### ISSUE TITLE
Add support for ITRF2020

### ISSUE THREAD

**Issue by BatchelorJ** [icsm-au/DynAdjust#206]
ITRF2020 is the new realization of the International Terrestrial Reference System. An enhancement to DynAdjust is required to support data input, transformation and output in this new realization.

A full set of transformation parameters from ITRF2020 to past ITRFs is available here:
https://itrf.ign.fr/docs/solutions/itrf2020/Transfo-ITRF2020_TRFs.txt

**Comment by ValZapod** [comment]
This should be done before 27 November when GPS will move to new IGS20 PSO (phase center offset) in all satellites.

https://itrf.ign.fr/en/solutions/transformations
https://igs.org/news/igs20/

**Comment by ValZapod** [comment]
IGS20 oficially added in December 2022. https://epsg.org/crs_10176/IGS20.html?sessionkey=jxx6qe2652

**Comment by rogerfraser** [comment]
Thanks @BatchelorJ and @ValZapod.  ITRF2020 will be supported in 1.2.7
