### ISSUE TITLE
Column overrun of DNA Measurement ID when converting from DynaML format

### ISSUE THREAD

**Issue by JasonHeritage** [icsm-au/DynAdjust#216]
**Description**
When converting from DynaML format to DNA format, the Measure ID column sometimes overruns the allocated character positions:

Example direction from DynaML file:
`<DnaMeasurement>
    <Type>D</Type>
    <Ignore/>
    <First>316000053114</First>
    <Second>316000053118</Second>
    <Value>75.4314474000</Value>
    <StdDev>119529.77531994</StdDev>
    <Total>1</Total>
    <Source>2000001769647</Source>
    <MeasurementID>23091906</MeasurementID>
    <Directions>
      <Ignore/>
      <Target>316000050887</Target>
      <Value>255.2421766000</Value>
      <StdDev>4185.65965055</StdDev>
      <MeasurementID>23091906</MeasurementID>
    </Directions>
  </DnaMeasurement>`

Corresponding direction from conversion:
![image](https://user-images.githubusercontent.com/44486698/231927924-17b957e5-174e-4dd6-b413-afcb2e5b6671.png)

**Steps to reproduce**
1. The DynaML MSR and STN files are attached, run the following command in CMD or Powershell in Windows: 
`import -n measurement_id_bug .\stn.xml .\msr.xml -r GDA2020 --output-msr-to-stn --export-dna-files`

2. Open the measurement_id_bug.msr file in a text editor, and search for Measurement ID: 23091906
3. The Meausrement ID for the first line of the direction begins at character 146, instead of 145, resulting in truncation of the ID, if bespoke parsing scripts are not aware of the overrun

**Screenshots**
None

**Operating system**
Windows 11
Dynadjust 1.2.7

**Additional context**
None

[measurement_id_bug.zip](https://github.com/icsm-au/DynAdjust/files/11228372/measurement_id_bug.zip)

**Comment by JasonHeritage** [comment]
I have an additional example of an overrun issue, this time occurring for a distance

![image](https://user-images.githubusercontent.com/44486698/232374087-1699f327-f425-4f01-9bcb-84faabc3d1d6.png)

The distance standard deviation is unusually high. Is it possible to increase column widths to allow for very large values?

Attached is the DynaML from which the .MSR was derived.
[343900000174.zip](https://github.com/icsm-au/DynAdjust/files/11246060/343900000174.zip)

**Comment by rogerfraser** [comment]
Thanks @JasonHeritage. The current width (9 chars) caters for a maximum standard deviation of 999999999 metres or seconds.  For values this large, decimetres, centimetres and millimetres don't make a lot of practical sense, nor do they bear any noticeable influence.

In lieu of increasing the width, it might be more pragmatic to round the value in the first instance and, should the standard deviation exceed 999999999, revert to scientific precision. 

For the examples provided in the images above, this would mean rounding 119529.775 seconds to 119529.78 and 320534.916 metres to 320534.92.  I would be surprised if this resulted in any noticeable influence, but you may want to check this.  For this analysis, it might be worth reconsidering a 320 km standard deviation on a 13.25 metre distance!

**Comment by JasonHeritage** [comment]
Hi @rogerfraser ,

yes, these values are way too large. The issue we're facing is that we rely on parsing the DNA format .MSR file. 
When converted from DynaML, the conversion results in column overflow due to the large values in the DynaML msr.xml.
Possible fixes:
- we modify the parsing script of DNA files
- round large values at conversion from DynaML to DNA (might not be the best option, best to keep raw data)
- increase column size of DNA format
I'm happy with any option

**Comment by rogerfraser** [comment]
I'm happy to apply a fix to automatically round these values on conversion (option 2).  This will be available in the next release.
