### ISSUE TITLE
Expand adjusted coordinates output formats

### ISSUE THREAD

**Issue by harry093** [icsm-au/DynAdjust#22]
Does it make sense to allow DynAdjust to output adjusted coordinates in a variety of formats?

**Comment by rogerfraser** [comment]
Sorry, not sure I understand the question - could you please clarify the requirement.

**Comment by harry093** [comment]
In addition to the fixed formatted output, would there be any use in allowing the output to be, say, csv or some other format, such as a format that allows the data to be read the data in a GIS program?

This is not a high priority, but was just a thought I had after there was a request to be able to read in comma separated data.

**Comment by rogerfraser** [comment]
This issue has been conflated with issue https://github.com/icsm-au/DynAdjust/issues/3 and repurposed as issue https://github.com/icsm-au/DynAdjust/issues/51
