### ISSUE TITLE
dynadjust-log-file : does not have a file at the output location referenced

### ISSUE THREAD

**Issue by tekwen** [icsm-au/DynAdjust#220]
**Description**
In the .dnaproj file there is reference to a log file: `dynadjust-log-file`

It does not look like this file gets written anywhere? There is no file with that name in the folder at the location referenced.

**Screenshots**
![image](https://user-images.githubusercontent.com/4932411/236315760-549d9330-07bf-4dfd-a55a-613073af1e1e.png)

**Operating system**
 - [Windows]
- [10]

**Additional context**
This is not affecting anything, and not sure if it really falls under the category of a bug. Just noticed it and wondered if there should be a file written, or if this is something that's yet to be implemented.

**Comment by rogerfraser** [comment]
Thanks @tekwen. 

The dynadjust log file should be created when **dynadjust** is executed.

Are you able to verify if this file is created when executing the following:

```
$> dynadjust -n <project-name> --import --adjust
```

**Comment by tekwen** [comment]
Aha! That's the trick. I see it now. Thanks @rogerfraser 
```
+---------------------------------------------------------------------------
+ Title:        dynadjust - DynAdjust 2022.
+ Description:  Geodetic network adjustment software
+ Version:      1.2.7, Release (64-bit)
+ Build:        Apr  4 2023, 14:40:56 (MSVC++ 17.1, VS2022)
+ Copyright:    (C) 2022 Geoscience Australia.
                This software is released under the Apache License.
+ Contact:      geodesy@ga.gov.au
+---------------------------------------------------------------------------


+ Executable   Start date and time      End date and time        Exit status              
------------------------------------------------------------------------------------------
+ import       12-05-2023 8:37:15 AM    12-05-2023 8:37:15 AM    Ended successfully.
+ adjust       12-05-2023 8:37:15 AM    12-05-2023 8:37:15 AM    Ended successfully.


+ DynAdjust finished successfully.

```
