### ISSUE TITLE
Observations with Standard Deviation of Zero

### ISSUE THREAD

**Issue by KentWheeler** [icsm-au/DynAdjust#23]
If an adjustment contains a standard deviation of zero, the adjustment will fail and throw a Cholesky factorisation failure. However, with some simple checks, it would be nicer if this error was a little more descriptive.

**Comment by rogerfraser** [comment]
This is a good idea, and has been a long-overdue enhancement.  Will add it to the next release

**Comment by rogerfraser** [comment]
This has been addressed in the latest code enhancements.
