### ISSUE TITLE
SQL export - SQLite or PostgreSQL

### ISSUE THREAD

**Issue by davecollett** [icsm-au/DynAdjust#3]
It would be great to be able to export results from 'adjust' to an SQLite database or SQL-dump format for use by other applications

**Comment by rogerfraser** [comment]
Not sure if the demand for SQLite remains, or how high that demand is.  In looking into options to export adjustment output to a better exchange format for other applications, I am wondering if JSON would be a suitable format.
Thoughts?

**Comment by rogerfraser** [comment]
This issue has been conflated with issue https://github.com/icsm-au/DynAdjust/issues/22 and repurposed as issue https://github.com/icsm-au/DynAdjust/issues/51
