### ISSUE TITLE
Adjust.exe: Measurement ID and Cluster ID seems not to be implemented. Correct?

### ISSUE THREAD

**Issue by slatham64** [icsm-au/DynAdjust#40]
Measurement ID and Cluster ID are documented on page 164 and page 194 of the DynAdjust manual.
It seems that this facility is not implemented when I tested it some time ago.
It would be convenient if this facility was implemented at least for the measurement ID for files like the national adjustment which have repeated measurements between station pairs, groups or clusters.

**Comment by rogerfraser** [comment]
Measurement ID and Cluster ID will be printed to the adjustment output file (*.adj), upon passing the optional argument --output-databse-ids, **if the respective IDs have been supplied within the input measurement file in the DNA MSR format**.  Database IDs should be entered in columns 143-152, as specifiec in Table B.3, page 176.  If these values have not been entered in the MSR file on input, Msr ID and Cluster ID columns the adj file (Table C.6, page 206) will be empty.

Please re-raise this as an issue if this feature is broken or is not behaving as expected.

**Comment by slatham64** [comment]
Roger,

I have not been able to get this to work when following these instructions.

The columns in the .adj file are filled with zeroes.

Have you got sample files where this functionality works?

I cannot find the appropriate line for the unique measurement ID in the .xml schema.

I value your input.

Regards,

Stephen

**Comment by rogerfraser** [comment]
Hi Steve,

Attached is a (mocked up) DNA MSR file which shows the use of database IDs.  The commands to reproduce the ADJ file, which contains the respective database IDs from input, are as follows:

import -n jda .\jurisdiction-5.stn .\jurisdiction-5.msr
geoid jda -g C:\data\dist\ausgeoid09.gsb --convert
segment jda --min 50 --max 50
adjust jda --phased --output-database --output-adj-msr

Hope this helps.  Please advise if you still have any further questions or concerns.

Kind regards, Roger.
