### ISSUE TITLE
Add enhancement. Please implement Measurement ID and Cluster ID for DynaML

### ISSUE THREAD

**Issue by slatham64** [icsm-au/DynAdjust#42]
DynAdjust manual v1.0, and earlier versions, detail functionality for Measurement ID and Cluster ID but this functionality currently only applies to dna format files and not DynaML files.

**Comment by rogerfraser** [comment]
This issue has now been resolved by pull request https://github.com/icsm-au/DynAdjust/pull/47, merged into the main branch.
