### ISSUE TITLE
Incorrect calculation of --output-adj-gnss-units

### ISSUE THREAD

**Issue by KentWheeler** [icsm-au/DynAdjust#46]
Below is a simple adjustment that demonstrates the error.
I have  created a minimally constrained adjustment with a single baseline. The outputed  coordinates include E, N and h. Therefore the enu of the baseline should match the differences between these coordiantes.

```
'Adjusted Measurements
------------------------------------------

M Station 1           Station 2           Station 3           *  C            Measured           Adjusted  Correction     Meas. SD      Adj. SD     Residual     N-stat     T-stat  Pelzer Rel  Pre Adj Corr    Outlier?
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
G BLV171T             GNAN92                                     e         -11382.7336        -11382.7336      0.0000       0.0018       0.0018       0.0000       0.00       0.00      999.99        0.0000            
G BLV171T             GNAN92                                     n           9368.8594          9368.8594      0.0000       0.0020       0.0020       0.0000       0.00       0.00      999.99        0.0000            
G BLV171T             GNAN92                                     u              2.4746             2.4746      0.0000       0.0071       0.0071       0.0000       0.00       0.00      999.99        0.0000            


Adjusted Coordinates
------------------------------------------

Station             Const       Easting       Northing    Zone      Latitude      Longitude   H(Ortho) h(Ellipse)              X              Y              Z       SD(e)     SD(n)    SD(up)  Description
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BLV171T             FFF     405941.7567   6471711.2962      50 -31.531147365  116.001961772    24.3065    -6.8274  -2376746.2172   4871875.8176  -3349750.0115      0.0018    0.0020    0.0071  
GNAN92              CCC     394476.8845   6480972.9355      50 -31.480709684  115.530688632    45.0850    12.7029  -2368686.7987   4881316.4602  -3341796.2578      0.0000    0.0000    0.0000  
'
```

**Comment by sfull** [comment]
G'day @KentWheeler ,

Thanks for your submission.

The enu (East, North, Up) values reported by DynAdjust for the baseline are in a **local topocentric reference frame** located at the "From" point of the baseline. The values are computed by applying a rotation matrix (based on the Lat/Long of the "From" point) to the dX, dY, dZ components of the baseline.

As such, the enu values **will **not**** match a dEasting, dNorthing, dH computed from Projected Grid Coordinates (e.g. MGA Zone 50). You would be comparing apples to pears ;-)

You can find detailed information on the local reference frame (enu), rotation matrices, etc. in Section 4.2.3 (Local Reference Frame) of the DynAdjust User Manual.

If you would like a spreadsheet that implements the approach in Section 4.2.3 of the user guide, please let me know.

**Comment by KentWheeler** [comment]
@sfull, Thanks for your reply and the reference, I understand what this is doing now. I believe the --output-adj-gnss-units 2 & 3 is using the same time of coordinate system referenced to the from station, I will need to think of another way of extracting the information that I want.
