### ISSUE TITLE
"Master" DynaML Schema in repo?

### ISSUE THREAD

**Issue by sfull** [icsm-au/DynAdjust#50]
G'day All,

I haven't been able to find a "master" version of the DynaML Schema (DynaML.xsd) in the repo. There is a version in /sampleData but it doesn't appear to be a master version as it's missing elements that are present in the documentation (e.g. the DnaXMLFormat type of "Combined File").

Would it be possible to add the current master version to the repo and track it from now on? Perhaps in the /resources folder?

**Comment by rogerfraser** [comment]
Hi Simon,

I've just uploaded a new version of the schema to the /[sampleData](https://github.com/icsm-au/DynAdjust/tree/master/sampleData) folder.  Is this okay, or would you rather see it the /resources folder?

**Comment by sfull** [comment]
@rogerfraser , I'm good with it in the /sampleData folder. Just wanted to make sure it was being tracked in the repo.. Thanks for updating it.
