### ISSUE TITLE
Incorrect SD when reporting results

### ISSUE THREAD

**Issue by harry093** [icsm-au/DynAdjust#56]
When the option --report-results is used some of the information output differs to that output during the adjustment. For example, an adjustment was done and the adjusted measurements were sorted by n-stat. The --report-results option was then use to output the adjusted measurements in the order that they were input to the adjustment. One measurement, a direction set, had an Adj. SD and a Corr. SD that was different to those output during the adjustment, which also caused the n-stat to change significantly.

**Comment by rogerfraser** [comment]
This issue appears to manifest in extremely large datasets (e.g. national adjustment) only, not with smaller datasets (e.g. statewide adjustments). After considerable investigation and testing, I am unable to replicate this issue with smaller datasets.  Help is required to identify/share a smaller dataset where this issue can be replicated and resolved.
