### ISSUE TITLE
Not found dll

### ISSUE THREAD

**Issue by zvezdochiot** [icsm-au/DynAdjust#68]
System: Win10

Release: https://github.com/icsm-au/DynAdjust/releases/tag/v1.0.3

Type:
```cmd
adjust
```

Dll not found:
* mkl_tbb_thread.dll
* msvcp110.dll
* msvcr110.dll
* tbb.dll

**Comment by rogerfraser** [comment]
These libraries are third party libraries shipped by Microsoft and Intel.

* **mkl_tbb_thread.dll** and **tbb.dll** are shipped as part of Intel's Math Kernel Library (MKL) and Threaded Building Blocks (TBB). See <https://software.seek.intel.com/performance-libraries> for accessing these run time binaries.

* **msvcp110.dll** and **msvcr110.dll** are shipped as part of the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. Visit <https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads> or <https://visualstudio.microsoft.com/downloads/> > _Other Tools and Frameworks_ > _Microsoft Visual C++ Redistributable for Visual Studio 2019_ to access the correct version for your system (32-bit or 64-bit).

**Comment by zvezdochiot** [comment]
Hi @rogerfraser .

Good. Maybe you should add this to the "Windows build requirements"? Or somewhere nearby?

**Comment by rogerfraser** [comment]
Thanks @zvezdochiot.  Good idea - the need to download these resources is mentioned in the [DynAdjust compilation in Windows](https://github.com/rogerfraser/DynAdjust/blob/master/resources/dynadjust-compilation-in-windows.pdf) PDF in the [resources](https://github.com/rogerfraser/DynAdjust/tree/master/resources) folder, but only the context of compiling.  I suppose what is needed are some instructions for runtime execution for those not able or wanting to compile.

**Comment by rogerfraser** [comment]
README.md has been updated with these suggestions.  Thank you @zvezdochiot.
