### ISSUE TITLE
List minimum requirements

### ISSUE THREAD

**Issue by harry093** [icsm-au/DynAdjust#7]
Create a text file listing the minimum versions of the various libraries/programs needed to compile DynAdjust

**Comment by harry093** [comment]
@rogerfraser, I have reopened this is light of #14. I think it's important that this information is easily accessible and currently it is only documented in this closed issue. We should also include the requirements for plotting. I am happy to put together a complete list for compiling under LInux, could you outline what is required for the Windows build?

**Comment by rogerfraser** [comment]
I suggest putting this in the [https://github.com/icsm-au/DynAdjust/tree/master/resources](resources) folder
