### ISSUE TITLE
Column overrun on ADJ file

### ISSUE THREAD

**Issue by jameslevershadelwp** [icsm-au/DynAdjust#78]
On erroneous output in some columns, the data overruns into the next columns. This makes it extremely difficult in automatically parsing results. Can you truncate these before output, possibly go to scientific if it breaches 0 decimal places?

The adjustment sd is so large it runs into the residual columns when I parse the columns using the specified column details in the manual I get 

240009879.931 and 2240009879.9310

rather than the actual

240009879.9312 and 2240009879.9310

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/49735855/100568373-27d1dd80-331f-11eb-9656-6c6169e3a249.png">

Please see attached adj file, I had to change it to text to upload.

[TP325001Y.simult.txt](https://github.com/icsm-au/DynAdjust/files/5613786/TP325001Y.simult.txt)

**Comment by jameslevershadelwp** [comment]
[TP325001Y.stn.txt](https://github.com/icsm-au/DynAdjust/files/5619188/TP325001Y.stn.txt)
[TP325001Y.msr.txt](https://github.com/icsm-au/DynAdjust/files/5619190/TP325001Y.msr.txt)

**Comment by stratiform** [comment]
Just tested the v1.1.0 release on data with adjustment issues, and it appears that not all the columns have had their overflows fixed - see below ADJ file, in particular "adjusted" and/or "correction" columns.
[690d1ab601ca44f18ec5e08bf1a1858c.phased.adj.txt](https://github.com/icsm-au/DynAdjust/files/5999636/690d1ab601ca44f18ec5e08bf1a1858c.phased.adj.txt)

Further to this, the result in the COR file are also still overflowing - see below.
[690d1ab601ca44f18ec5e08bf1a1858c.phased.cor.txt](https://github.com/icsm-au/DynAdjust/files/5999638/690d1ab601ca44f18ec5e08bf1a1858c.phased.cor.txt)

Is it possible for the fixed to be applied to all columns in all files? Our parsing priorities are the ADJ file, APU file, and COR file.

Full input data and adjustment params:
[PS527037N.zip](https://github.com/icsm-au/DynAdjust/files/5999640/PS527037N.zip)
