### ISSUE TITLE
Default Reference Frame in User's Guide

### ISSUE THREAD

**Issue by wapayze** [icsm-au/DynAdjust#80]
Hi,
This isn't a big issue. Section 3.3.1 of the User's Guide still says that the default reference frame on import is GDA94.
Cheers,
Bill.

**Comment by harry093** [comment]
Good pick up @wapayze! Thanks for letting us know

**Comment by jhaasdyk-au** [comment]
Greetings Roger! A nice easy issue for my first posting to the DynAdjust issues logs.
(By the way, I'm really enjoying the User Guide... I find it concise yet informative, and easy to read. 
Many thanks for all of the work you've put in here!)

The User Guide (release 1.2.6, Aug 2022) requires an exhaustive update to reflect:
- Update of **default reference frame** from GDA94 to GDA2020

The following sections are incorrect (unchanged to reflect earlier updates to defaults):
- **pg 8, Section1.3.2 Program execution and command line options** indicates:
  _"For example [...] **import** will adopt the Geocentric Datum of Australia 1994 (GDA94) as the default value"_
- **pg 175,  Table A.4 Reference Frame Options**  _"The default reference frame is GDA94"_
- **pg 193, Last paragraph**  _"...default reference frame ... GDA94"_

The use of 'Default = GDA94' is not strictly incorrect in the following examples, but is now outdated.
- **pg 22, Figure 3.1**   
- **pg 32, Lower-most callout box** 
- **pg 194, Table B.1    (if space permits...)
- **pg 218, C.2 Import log file (IMP) example callout**

**Comment by jhaasdyk-au** [comment]
On a related matter, 
- **pg 193, Last paragraph**  indicates  _"DynAdjust will set ... default geoid model... to AUSGeoid09"_
Is this still true?  It appears that geoid.exe (now?) requires explicit declaration of the geoid file. 

In anycase, an exhaustive update of documentation to adopt and advise on AUSGeoid2020 is certainly in order. 
If software changes are required, then that is a more significant issue.
