### ISSUE TITLE
Leave unused stations out of adj.xml file

### ISSUE THREAD

**Issue by harry093** [icsm-au/DynAdjust#85]
Would it be possible to modify DynAdjust to leave unused stations out of the .adj.xml file?

The --flag-unused-stations import option leaves flagged stations out of all output files except the adj.xml file. The national adjustment reads this file in first when performing the next adjustment. This leads to a build up of stations that have been removed in this file. This can cause confusion when importing this file into programs like Zed to analyse the adjustment.

**Comment by rogerfraser** [comment]
Yes, that's entirely possible.  Thanks for the suggestion.
